### ISSUE TITLE
How to support CORS 

### ISSUE THREAD

**Issue by henyana** [frank505/PHP-SLIM-4-API-WITH-JWT#1]
Hi franklin,
It is a nice ropository. 
I khow this from your channel witch is a great share.
I wonder it can support for CORS implemtation.
I am facing the prolem with it.

`<?php
use Slim\App;

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Server\RequestHandlerInterface;
use Slim\Factory\AppFactory;
use Slim\Routing\RouteCollectorProxy;
use Slim\Routing\RouteContext;

return function (App $app)
{
  $app->getContainer()->get('settings');
  // $app->addBodyParsingMiddleware();

  // This middleware will append the response header Access-Control-Allow-Methods with all allowed methods
  $app->add(function (Request $request, RequestHandlerInterface $handler): Response {
    $routeContext = RouteContext::fromRequest($request);
    $routingResults = $routeContext->getRoutingResults();
    $methods = $routingResults->getAllowedMethods();
    $requestHeaders = $request->getHeaderLine('Access-Control-Request-Headers');

    $response = $handler->handle($request);

    $response = $response->withHeader('Access-Control-Allow-Origin', 'http://localhost:8081');
    $response = $response->withHeader('Access-Control-Allow-Methods', implode(',', $methods));
    $response = $response->withHeader('Access-Control-Allow-Headers', $requestHeaders);

    // Optional: Allow Ajax CORS requests with Authorization header
    $response = $response->withHeader('Access-Control-Allow-Credentials', 'true');

    return $response;
  });

  $app->addRoutingMiddleware();

  $app->add(
      new \Tuupola\Middleware\JwtAuthentication([
          "ignore"=>["/api/auth/login","/api/auth/register"],
          "secret"=>\App\Interfaces\SecretKeyInterface::JWT_SECRET_KEY,
          "error"=>function($response,$arguments)
          {
              $data["success"] = false;
              $data["response"]=$arguments["message"];
              $data["status_code"]= "401";

              return $response->withHeader("Content-type","application/json")
                  ->getBody()->write(json_encode($data,JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT ));
          }
      ])
  );
  $app->addErrorMiddleware(true,true,true);

  // Allow preflight requests
  // Due to the behaviour of browsers when sending a request,
  // you must add the OPTIONS method. Read about preflight.
  $app->options('/api/auth/login', function (Request $request, Response $response): Response {
      // Do nothing here. Just return the response.
      return $response;
  });

};`

but when I did requested POST http://localhost:8080/api/auth/login,  the server always return 400 response error:

`{"success":false,"response":{"email":{"Email":"Email must be valid email"},"password":{"Password":"Password must not be empty"}}}`

How I can fix this? Any suggestion?

**Comment by frank505** [comment]
good morning i was going to make a video with react on the second part of that series but i have had a whole lot of work the past few months, to fix CORS issue you will need to set first set a CORS middleware which i suppose you must have done and then set an options request either for each route or you could use a regular expression to match all the routes at the same time.
   something like this:
 ```
 $app->post('/create-guest', [GuestEntryController::class, 'createGuest']);

    // Allow preflight requests for /
    $app->options('/create-guest', function (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface {
        return $response;
    });
```

**Comment by henyana** [comment]
Good morning, well here it is afternoon so I am from the future... hehe, just kidding.

I've add on the router.php for the auth/login

`    // Allow preflight requests for /
   $app->options('/api/auth/login', function (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface {
        return $response;
    });`

but I still have the same response with 400.

`{"success":false,"response":{"email":{"Email":"Email must be valid email"},"password":{"Password":"Password must not be empty"}}}`

it seem the server didnot  catch the request POST I am using axios

**Comment by henyana** [comment]
I am  sorry my mistake, the problem is on the frontend side, now it's fixed thank you!
