### ISSUE TITLE
Support for body form-data for uploading file

### ISSUE THREAD

**Issue by henyana** [frank505/PHP-SLIM-4-API-WITH-JWT#2]
Hi Frank,

Currenlty I have test this request method all using the Query Params in the Postman wich are works as expected.

But when I've changed the request method using Body form-data 
and disable the Query Params, all the requests are stuck in the validators.
This is mean that the Body form-data is not catch by the CustomRequestHandler.php.

I need to upload a file to the server which is available in the Body form-data for the file.
Any suggestions for solving my problem?

**Comment by frank505** [comment]
@henyana i have noted this as others have also complained in my php slim 3 series one way to fix this would be to convert the file to base64string and upload although thats far from the best solution, i already have a perfect solution and would show it in my next video at the beginning the react section of the series.
   Hopefully if i have some freetime this month .

**Comment by henyana** [comment]
I was already did that your solution and it's works. Can't wait to see the next screencast on youtube.

**Comment by henyana** [comment]
Hi Frank,
I close this because already have solution.
The file upload its done by converted to base64 string then upload via json string.
